//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ReportID { get; set; }
        public int itemQty { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual REPORT REPORT { get; set; }
    }
}
