//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPORT()
        {
            this.ORDERs = new HashSet<ORDER>();
        }
    
        public int ReportID { get; set; }
        public string ReportDesc { get; set; }
        public System.DateTime ReportDate { get; set; }
        public int ProductID { get; set; }
        public int ItemQty { get; set; }
        public int CategoryID { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
