//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPDATE
    {
        public int UpdateID { get; set; }
        public int EmployeeID { get; set; }
        public int ProductID { get; set; }
        public string UpdateDesc { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
